### PR TITLE
Repository

### PR DESCRIPTION
**Pull request by trooblet**
Updating the main code base for unit testing to be performed

### CODE REVIEW

**Comment by jdagnin** [comment]
its not going through due to merge conflicts, we should have used the git flow workflow correctly to avoid this. making so many changes from multiple people in a single branch is not a good idea, we need to keep separate features on separate branches and make smaller commits and smaller pull requests otherwise it will take forever to review all the code changes

**Comment by trooblet** [comment]
I was doing only small commits but no one was reviewing them as I put them through.

There’s like 41 commits in the repository branch to go through.

On 12/10/2019, at 1:10 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


its not going through due to merge conflicts, we should have used the git flow workflow correctly to avoid this. making so many changes from multiple people in a single branch is not a good idea, we need to keep separate features on separate branches and make smaller commits and smaller pull requests otherwise it will take forever to review all the code changes

**Comment by jdagnin** [comment]
ok, i have just pushed it all through - i had to make changes to server.js

**Comment by trooblet** [comment]
Okay thanks Ben maybe we can make a document which gives a standard usage of commits and pull requests? Just to avoid mixing it up in future.

On 12/10/2019, at 1:24 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, i have just pushed it all through - i had to make changes to server.js

**Comment by jdagnin** [comment]
what we should be doing is creating a new branch for each feature, based from develop, then once we have coded we pull from develop into that feature branch to get it up to date with develop. then once local tests pass, we push that feature branch back into develop. then test on develop, and after that we review code to push into master and deploy

**Comment by jdagnin** [comment]
Yeah, i think we could use a document for it

**Comment by trooblet** [comment]
How granular do you want that? One per epic US or per functional components?

Sent from my iPhone

On 12/10/2019, at 1:26 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


what we should be doing is creating a new branch for each feature, based from develop, then once we have coded we pull from develop into that feature branch to get it up to date with develop. then once local tests pass, we push that feature branch back into develop. then test on develop, and after that we review code to push into master and deploy

**Comment by jdagnin** [comment]
i think it would depend on how many people we have working on the story - if there are a lot of features for a story, it should be broken down more so we dont overstep each other, and push / pull as frequently as possible so we are always up to date with the branch

**Comment by trooblet** [comment]
Okay the way I was committing was putting code through for each feature I created for example uploading a file, then one for reading a file, and another for pushing the data into MongoDB which is unfinished atm


On 12/10/2019, at 1:31 PM, Ben <notifications@github.com<mailto:notifications@github.com>> wrote:


i think it would depend on how many people we have working on the story - if there are a lot of features for a story, it should be broken down more so we dont overstep each other, and push / pull as frequently as possible so we are always up to date with the branch

**Pull request merged**
